### ISSUE TITLE
Login Token Refresh

### ISSUE THREAD

**Issue by thomaszehetner** [axonivy-market/metaproc-connector#9]
Hi @ivy-sgi ,

we are currently trying to setup the Metaproc-Connector for our RPA demos.

In addition to some problems on the Metaproc side, we also noticed that there seems to be a refresh problem with the token of the RPA interface to Metaproc on the Axon Ivy side. The auth token feature implementation seems to somehow cache the login but when the token expires it is not refreshed. 
(Feedback Metaproc developer: "the token in the HTTP logs in the AxonIvy designer is the same for every execution. However, when I call up the login using postman, for example, I always get a different new token. When I restart the AxonIvy app/designer, the first execution always seems to work.")

Can you please revise the Auth implementation here? Possibly after consultation with Ivyteam...

Thx & br
Thomas

**Comment by ivy-sgi** [comment]
Hi @thomaszehetner We will check it!

**Comment by tutn-axonivy** [comment]
Hi @thomaszehetner, what kind of token does this connector use to authenticate?

**Comment by thomaszehetner** [comment]
… i do not know technical details. Please check the mentioned java implementation or contact ivy core development.

Br
Thomas

Von: Tu Thanh Nguyen ***@***.***>
Gesendet: Dienstag, 23. April 2024 12:04
An: axonivy-market/metaproc-connector ***@***.***>
Cc: Thomas Zehetner ***@***.***>; Mention ***@***.***>
Betreff: Re: [axonivy-market/metaproc-connector] Login Token Refresh (Issue #9)


Hi @thomaszehetner<https://github.com/thomaszehetner>, what kind of token does this connector use to authenticate?

**Comment by tutn-axonivy** [comment]
Hi @thomaszehetner, how can we contact to Metaproc developer to know how long is the expiration of the token? Or you can suggest which duration is most suitable. Thanks.

**Comment by ivy-rew** [comment]
if it's a classic JWT token you are receiving, you could check the expiration time manually.
auth0's JWT library may help with you decoding the token and reading its claims.
https://mvnrepository.com/artifact/com.auth0/java-jwt/4.4.0

better and more standard would be to use our oauth2-URI factories, so authentication request are automatically fired, when 401/3 statuses are being thrown by the service, or when we do not yet have a token.
see ch.ivyteam.ivy.rest.client.oauth2.uri.OAuth2UriProperty
and its appliance in https://github.com/axonivy-market/msgraph-connector/blob/master/msgraph-oauth-feature/src/com/microsoft/auth/OAuth2Feature.java#L120
or https://github.com/axonivy-market/docusign-connector/blob/master/docusign-connector/src/com/axonivy/connector/docusign/auth/OAuth2Feature.java

**Comment by ivy-rew** [comment]
let's wait till we have a tested and working solution: https://github.com/axonivy-market/metaproc-connector/pull/15

**Comment by ivy-sgi** [comment]
Fixed and released new version on 27.05.2024.
